#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHOP.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="hsk")]
	public partial class hskDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertcategoria(categoria instance);
    partial void Updatecategoria(categoria instance);
    partial void Deletecategoria(categoria instance);
    partial void Insertcidade(cidade instance);
    partial void Updatecidade(cidade instance);
    partial void Deletecidade(cidade instance);
    partial void Insertestado(estado instance);
    partial void Updateestado(estado instance);
    partial void Deleteestado(estado instance);
    partial void Insertsexo(sexo instance);
    partial void Updatesexo(sexo instance);
    partial void Deletesexo(sexo instance);
    partial void Insertstatuspedido(statuspedido instance);
    partial void Updatestatuspedido(statuspedido instance);
    partial void Deletestatuspedido(statuspedido instance);
    partial void Insertcliente(cliente instance);
    partial void Updatecliente(cliente instance);
    partial void Deletecliente(cliente instance);
    partial void Insertitenspedido(itenspedido instance);
    partial void Updateitenspedido(itenspedido instance);
    partial void Deleteitenspedido(itenspedido instance);
    partial void Insertpedido(pedido instance);
    partial void Updatepedido(pedido instance);
    partial void Deletepedido(pedido instance);
    partial void Insertproduto(produto instance);
    partial void Updateproduto(produto instance);
    partial void Deleteproduto(produto instance);
    partial void Insertusuario(usuario instance);
    partial void Updateusuario(usuario instance);
    partial void Deleteusuario(usuario instance);
    #endregion
		
		public hskDataContext() : 
				base(global::SHOP.Properties.Settings.Default.hskConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public hskDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public hskDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public hskDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public hskDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<categoria> categorias
		{
			get
			{
				return this.GetTable<categoria>();
			}
		}
		
		public System.Data.Linq.Table<cidade> cidades
		{
			get
			{
				return this.GetTable<cidade>();
			}
		}
		
		public System.Data.Linq.Table<estado> estados
		{
			get
			{
				return this.GetTable<estado>();
			}
		}
		
		public System.Data.Linq.Table<sexo> sexos
		{
			get
			{
				return this.GetTable<sexo>();
			}
		}
		
		public System.Data.Linq.Table<statuspedido> statuspedidos
		{
			get
			{
				return this.GetTable<statuspedido>();
			}
		}
		
		public System.Data.Linq.Table<cliente> clientes
		{
			get
			{
				return this.GetTable<cliente>();
			}
		}
		
		public System.Data.Linq.Table<itenspedido> itenspedidos
		{
			get
			{
				return this.GetTable<itenspedido>();
			}
		}
		
		public System.Data.Linq.Table<pedido> pedidos
		{
			get
			{
				return this.GetTable<pedido>();
			}
		}
		
		public System.Data.Linq.Table<produto> produtos
		{
			get
			{
				return this.GetTable<produto>();
			}
		}
		
		public System.Data.Linq.Table<usuario> usuarios
		{
			get
			{
				return this.GetTable<usuario>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.categorias")]
	public partial class categoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idcategorias;
		
		private string _tipo;
		
		private string _descricao;
		
		private EntitySet<produto> _produtos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidcategoriasChanging(int value);
    partial void OnidcategoriasChanged();
    partial void OntipoChanging(string value);
    partial void OntipoChanged();
    partial void OndescricaoChanging(string value);
    partial void OndescricaoChanged();
    #endregion
		
		public categoria()
		{
			this._produtos = new EntitySet<produto>(new Action<produto>(this.attach_produtos), new Action<produto>(this.detach_produtos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idcategorias", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idcategorias
		{
			get
			{
				return this._idcategorias;
			}
			set
			{
				if ((this._idcategorias != value))
				{
					this.OnidcategoriasChanging(value);
					this.SendPropertyChanging();
					this._idcategorias = value;
					this.SendPropertyChanged("idcategorias");
					this.OnidcategoriasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo", DbType="VarChar(45)")]
		public string tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				if ((this._tipo != value))
				{
					this.OntipoChanging(value);
					this.SendPropertyChanging();
					this._tipo = value;
					this.SendPropertyChanged("tipo");
					this.OntipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descricao", DbType="VarChar(45)")]
		public string descricao
		{
			get
			{
				return this._descricao;
			}
			set
			{
				if ((this._descricao != value))
				{
					this.OndescricaoChanging(value);
					this.SendPropertyChanging();
					this._descricao = value;
					this.SendPropertyChanged("descricao");
					this.OndescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="categoria_produto", Storage="_produtos", ThisKey="idcategorias", OtherKey="idcategoria")]
		public EntitySet<produto> produtos
		{
			get
			{
				return this._produtos;
			}
			set
			{
				this._produtos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_produtos(produto entity)
		{
			this.SendPropertyChanging();
			entity.categoria = this;
		}
		
		private void detach_produtos(produto entity)
		{
			this.SendPropertyChanging();
			entity.categoria = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cidade")]
	public partial class cidade : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CidadeId;
		
		private string _Nome;
		
		private System.Nullable<int> _EstadoId;
		
		private bool _Capital;
		
		private EntitySet<cliente> _clientes;
		
		private EntityRef<estado> _estado;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCidadeIdChanging(int value);
    partial void OnCidadeIdChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnEstadoIdChanging(System.Nullable<int> value);
    partial void OnEstadoIdChanged();
    partial void OnCapitalChanging(bool value);
    partial void OnCapitalChanged();
    #endregion
		
		public cidade()
		{
			this._clientes = new EntitySet<cliente>(new Action<cliente>(this.attach_clientes), new Action<cliente>(this.detach_clientes));
			this._estado = default(EntityRef<estado>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CidadeId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CidadeId
		{
			get
			{
				return this._CidadeId;
			}
			set
			{
				if ((this._CidadeId != value))
				{
					this.OnCidadeIdChanging(value);
					this.SendPropertyChanging();
					this._CidadeId = value;
					this.SendPropertyChanged("CidadeId");
					this.OnCidadeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(38) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoId", DbType="Int")]
		public System.Nullable<int> EstadoId
		{
			get
			{
				return this._EstadoId;
			}
			set
			{
				if ((this._EstadoId != value))
				{
					if (this._estado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEstadoIdChanging(value);
					this.SendPropertyChanging();
					this._EstadoId = value;
					this.SendPropertyChanged("EstadoId");
					this.OnEstadoIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Capital", DbType="Bit NOT NULL")]
		public bool Capital
		{
			get
			{
				return this._Capital;
			}
			set
			{
				if ((this._Capital != value))
				{
					this.OnCapitalChanging(value);
					this.SendPropertyChanging();
					this._Capital = value;
					this.SendPropertyChanged("Capital");
					this.OnCapitalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cidade_cliente", Storage="_clientes", ThisKey="CidadeId", OtherKey="cidade")]
		public EntitySet<cliente> clientes
		{
			get
			{
				return this._clientes;
			}
			set
			{
				this._clientes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="estado_cidade", Storage="_estado", ThisKey="EstadoId", OtherKey="EstadoId", IsForeignKey=true)]
		public estado estado
		{
			get
			{
				return this._estado.Entity;
			}
			set
			{
				estado previousValue = this._estado.Entity;
				if (((previousValue != value) 
							|| (this._estado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._estado.Entity = null;
						previousValue.cidades.Remove(this);
					}
					this._estado.Entity = value;
					if ((value != null))
					{
						value.cidades.Add(this);
						this._EstadoId = value.EstadoId;
					}
					else
					{
						this._EstadoId = default(Nullable<int>);
					}
					this.SendPropertyChanged("estado");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_clientes(cliente entity)
		{
			this.SendPropertyChanging();
			entity.cidade1 = this;
		}
		
		private void detach_clientes(cliente entity)
		{
			this.SendPropertyChanging();
			entity.cidade1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.estado")]
	public partial class estado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _EstadoId;
		
		private string _Sigla;
		
		private EntitySet<cidade> _cidades;
		
		private EntitySet<cliente> _clientes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEstadoIdChanging(int value);
    partial void OnEstadoIdChanged();
    partial void OnSiglaChanging(string value);
    partial void OnSiglaChanged();
    #endregion
		
		public estado()
		{
			this._cidades = new EntitySet<cidade>(new Action<cidade>(this.attach_cidades), new Action<cidade>(this.detach_cidades));
			this._clientes = new EntitySet<cliente>(new Action<cliente>(this.attach_clientes), new Action<cliente>(this.detach_clientes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int EstadoId
		{
			get
			{
				return this._EstadoId;
			}
			set
			{
				if ((this._EstadoId != value))
				{
					this.OnEstadoIdChanging(value);
					this.SendPropertyChanging();
					this._EstadoId = value;
					this.SendPropertyChanged("EstadoId");
					this.OnEstadoIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sigla", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string Sigla
		{
			get
			{
				return this._Sigla;
			}
			set
			{
				if ((this._Sigla != value))
				{
					this.OnSiglaChanging(value);
					this.SendPropertyChanging();
					this._Sigla = value;
					this.SendPropertyChanged("Sigla");
					this.OnSiglaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="estado_cidade", Storage="_cidades", ThisKey="EstadoId", OtherKey="EstadoId")]
		public EntitySet<cidade> cidades
		{
			get
			{
				return this._cidades;
			}
			set
			{
				this._cidades.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="estado_cliente", Storage="_clientes", ThisKey="EstadoId", OtherKey="uf")]
		public EntitySet<cliente> clientes
		{
			get
			{
				return this._clientes;
			}
			set
			{
				this._clientes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_cidades(cidade entity)
		{
			this.SendPropertyChanging();
			entity.estado = this;
		}
		
		private void detach_cidades(cidade entity)
		{
			this.SendPropertyChanging();
			entity.estado = null;
		}
		
		private void attach_clientes(cliente entity)
		{
			this.SendPropertyChanging();
			entity.estado = this;
		}
		
		private void detach_clientes(cliente entity)
		{
			this.SendPropertyChanging();
			entity.estado = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sexos")]
	public partial class sexo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private char _idsexos;
		
		private string _descricao;
		
		private EntitySet<cliente> _clientes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidsexosChanging(char value);
    partial void OnidsexosChanged();
    partial void OndescricaoChanging(string value);
    partial void OndescricaoChanged();
    #endregion
		
		public sexo()
		{
			this._clientes = new EntitySet<cliente>(new Action<cliente>(this.attach_clientes), new Action<cliente>(this.detach_clientes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idsexos", DbType="Char(1) NOT NULL", IsPrimaryKey=true)]
		public char idsexos
		{
			get
			{
				return this._idsexos;
			}
			set
			{
				if ((this._idsexos != value))
				{
					this.OnidsexosChanging(value);
					this.SendPropertyChanging();
					this._idsexos = value;
					this.SendPropertyChanged("idsexos");
					this.OnidsexosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descricao", DbType="VarChar(45)")]
		public string descricao
		{
			get
			{
				return this._descricao;
			}
			set
			{
				if ((this._descricao != value))
				{
					this.OndescricaoChanging(value);
					this.SendPropertyChanging();
					this._descricao = value;
					this.SendPropertyChanged("descricao");
					this.OndescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sexo_cliente", Storage="_clientes", ThisKey="idsexos", OtherKey="sexo")]
		public EntitySet<cliente> clientes
		{
			get
			{
				return this._clientes;
			}
			set
			{
				this._clientes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_clientes(cliente entity)
		{
			this.SendPropertyChanging();
			entity.sexo1 = this;
		}
		
		private void detach_clientes(cliente entity)
		{
			this.SendPropertyChanging();
			entity.sexo1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.statuspedido")]
	public partial class statuspedido : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idstatus;
		
		private string _descricao;
		
		private EntitySet<pedido> _pedidos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidstatusChanging(int value);
    partial void OnidstatusChanged();
    partial void OndescricaoChanging(string value);
    partial void OndescricaoChanged();
    #endregion
		
		public statuspedido()
		{
			this._pedidos = new EntitySet<pedido>(new Action<pedido>(this.attach_pedidos), new Action<pedido>(this.detach_pedidos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idstatus", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idstatus
		{
			get
			{
				return this._idstatus;
			}
			set
			{
				if ((this._idstatus != value))
				{
					this.OnidstatusChanging(value);
					this.SendPropertyChanging();
					this._idstatus = value;
					this.SendPropertyChanged("idstatus");
					this.OnidstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descricao", DbType="VarChar(45)")]
		public string descricao
		{
			get
			{
				return this._descricao;
			}
			set
			{
				if ((this._descricao != value))
				{
					this.OndescricaoChanging(value);
					this.SendPropertyChanging();
					this._descricao = value;
					this.SendPropertyChanged("descricao");
					this.OndescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="statuspedido_pedido", Storage="_pedidos", ThisKey="idstatus", OtherKey="statuspedido")]
		public EntitySet<pedido> pedidos
		{
			get
			{
				return this._pedidos;
			}
			set
			{
				this._pedidos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_pedidos(pedido entity)
		{
			this.SendPropertyChanging();
			entity.statuspedido1 = this;
		}
		
		private void detach_pedidos(pedido entity)
		{
			this.SendPropertyChanging();
			entity.statuspedido1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.clientes")]
	public partial class cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idclientes;
		
		private string _nome;
		
		private string _telefone;
		
		private System.Nullable<char> _sexo;
		
		private string _email;
		
		private string _endereco;
		
		private string _bairro;
		
		private string _numero;
		
		private string _cep;
		
		private int _uf;
		
		private System.Nullable<int> _cidade;
		
		private bool _status;
		
		private string _cpf_cnpj;
		
		private EntitySet<pedido> _pedidos;
		
		private EntityRef<cidade> _cidade1;
		
		private EntityRef<estado> _estado;
		
		private EntityRef<sexo> _sexo1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidclientesChanging(int value);
    partial void OnidclientesChanged();
    partial void OnnomeChanging(string value);
    partial void OnnomeChanged();
    partial void OntelefoneChanging(string value);
    partial void OntelefoneChanged();
    partial void OnsexoChanging(System.Nullable<char> value);
    partial void OnsexoChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnenderecoChanging(string value);
    partial void OnenderecoChanged();
    partial void OnbairroChanging(string value);
    partial void OnbairroChanged();
    partial void OnnumeroChanging(string value);
    partial void OnnumeroChanged();
    partial void OncepChanging(string value);
    partial void OncepChanged();
    partial void OnufChanging(int value);
    partial void OnufChanged();
    partial void OncidadeChanging(System.Nullable<int> value);
    partial void OncidadeChanged();
    partial void OnstatusChanging(bool value);
    partial void OnstatusChanged();
    partial void Oncpf_cnpjChanging(string value);
    partial void Oncpf_cnpjChanged();
    #endregion
		
		public cliente()
		{
			this._pedidos = new EntitySet<pedido>(new Action<pedido>(this.attach_pedidos), new Action<pedido>(this.detach_pedidos));
			this._cidade1 = default(EntityRef<cidade>);
			this._estado = default(EntityRef<estado>);
			this._sexo1 = default(EntityRef<sexo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idclientes", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idclientes
		{
			get
			{
				return this._idclientes;
			}
			set
			{
				if ((this._idclientes != value))
				{
					this.OnidclientesChanging(value);
					this.SendPropertyChanging();
					this._idclientes = value;
					this.SendPropertyChanged("idclientes");
					this.OnidclientesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="VarChar(45)")]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this.OnnomeChanging(value);
					this.SendPropertyChanging();
					this._nome = value;
					this.SendPropertyChanged("nome");
					this.OnnomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefone", DbType="VarChar(45)")]
		public string telefone
		{
			get
			{
				return this._telefone;
			}
			set
			{
				if ((this._telefone != value))
				{
					this.OntelefoneChanging(value);
					this.SendPropertyChanging();
					this._telefone = value;
					this.SendPropertyChanged("telefone");
					this.OntelefoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sexo", DbType="Char(1)")]
		public System.Nullable<char> sexo
		{
			get
			{
				return this._sexo;
			}
			set
			{
				if ((this._sexo != value))
				{
					if (this._sexo1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnsexoChanging(value);
					this.SendPropertyChanging();
					this._sexo = value;
					this.SendPropertyChanged("sexo");
					this.OnsexoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(45)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endereco", DbType="VarChar(45)")]
		public string endereco
		{
			get
			{
				return this._endereco;
			}
			set
			{
				if ((this._endereco != value))
				{
					this.OnenderecoChanging(value);
					this.SendPropertyChanging();
					this._endereco = value;
					this.SendPropertyChanged("endereco");
					this.OnenderecoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bairro", DbType="VarChar(45)")]
		public string bairro
		{
			get
			{
				return this._bairro;
			}
			set
			{
				if ((this._bairro != value))
				{
					this.OnbairroChanging(value);
					this.SendPropertyChanging();
					this._bairro = value;
					this.SendPropertyChanged("bairro");
					this.OnbairroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numero", DbType="VarChar(45)")]
		public string numero
		{
			get
			{
				return this._numero;
			}
			set
			{
				if ((this._numero != value))
				{
					this.OnnumeroChanging(value);
					this.SendPropertyChanging();
					this._numero = value;
					this.SendPropertyChanged("numero");
					this.OnnumeroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cep", DbType="VarChar(8)")]
		public string cep
		{
			get
			{
				return this._cep;
			}
			set
			{
				if ((this._cep != value))
				{
					this.OncepChanging(value);
					this.SendPropertyChanging();
					this._cep = value;
					this.SendPropertyChanged("cep");
					this.OncepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uf", DbType="Int NOT NULL")]
		public int uf
		{
			get
			{
				return this._uf;
			}
			set
			{
				if ((this._uf != value))
				{
					if (this._estado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnufChanging(value);
					this.SendPropertyChanging();
					this._uf = value;
					this.SendPropertyChanged("uf");
					this.OnufChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cidade", DbType="Int")]
		public System.Nullable<int> cidade
		{
			get
			{
				return this._cidade;
			}
			set
			{
				if ((this._cidade != value))
				{
					if (this._cidade1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncidadeChanging(value);
					this.SendPropertyChanging();
					this._cidade = value;
					this.SendPropertyChanged("cidade");
					this.OncidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Bit NOT NULL")]
		public bool status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cpf_cnpj", DbType="VarChar(14)")]
		public string cpf_cnpj
		{
			get
			{
				return this._cpf_cnpj;
			}
			set
			{
				if ((this._cpf_cnpj != value))
				{
					this.Oncpf_cnpjChanging(value);
					this.SendPropertyChanging();
					this._cpf_cnpj = value;
					this.SendPropertyChanged("cpf_cnpj");
					this.Oncpf_cnpjChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cliente_pedido", Storage="_pedidos", ThisKey="idclientes", OtherKey="idcliente")]
		public EntitySet<pedido> pedidos
		{
			get
			{
				return this._pedidos;
			}
			set
			{
				this._pedidos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cidade_cliente", Storage="_cidade1", ThisKey="cidade", OtherKey="CidadeId", IsForeignKey=true)]
		public cidade cidade1
		{
			get
			{
				return this._cidade1.Entity;
			}
			set
			{
				cidade previousValue = this._cidade1.Entity;
				if (((previousValue != value) 
							|| (this._cidade1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._cidade1.Entity = null;
						previousValue.clientes.Remove(this);
					}
					this._cidade1.Entity = value;
					if ((value != null))
					{
						value.clientes.Add(this);
						this._cidade = value.CidadeId;
					}
					else
					{
						this._cidade = default(Nullable<int>);
					}
					this.SendPropertyChanged("cidade1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="estado_cliente", Storage="_estado", ThisKey="uf", OtherKey="EstadoId", IsForeignKey=true)]
		public estado estado
		{
			get
			{
				return this._estado.Entity;
			}
			set
			{
				estado previousValue = this._estado.Entity;
				if (((previousValue != value) 
							|| (this._estado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._estado.Entity = null;
						previousValue.clientes.Remove(this);
					}
					this._estado.Entity = value;
					if ((value != null))
					{
						value.clientes.Add(this);
						this._uf = value.EstadoId;
					}
					else
					{
						this._uf = default(int);
					}
					this.SendPropertyChanged("estado");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sexo_cliente", Storage="_sexo1", ThisKey="sexo", OtherKey="idsexos", IsForeignKey=true)]
		public sexo sexo1
		{
			get
			{
				return this._sexo1.Entity;
			}
			set
			{
				sexo previousValue = this._sexo1.Entity;
				if (((previousValue != value) 
							|| (this._sexo1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._sexo1.Entity = null;
						previousValue.clientes.Remove(this);
					}
					this._sexo1.Entity = value;
					if ((value != null))
					{
						value.clientes.Add(this);
						this._sexo = value.idsexos;
					}
					else
					{
						this._sexo = default(Nullable<char>);
					}
					this.SendPropertyChanged("sexo1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_pedidos(pedido entity)
		{
			this.SendPropertyChanging();
			entity.cliente = this;
		}
		
		private void detach_pedidos(pedido entity)
		{
			this.SendPropertyChanging();
			entity.cliente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.itenspedido")]
	public partial class itenspedido : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _iditenspedido;
		
		private int _idpedido;
		
		private int _idproduto;
		
		private decimal _quantidade;
		
		private decimal _valor;
		
		private decimal _valortotal;
		
		private EntityRef<pedido> _pedido;
		
		private EntityRef<produto> _produto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OniditenspedidoChanging(int value);
    partial void OniditenspedidoChanged();
    partial void OnidpedidoChanging(int value);
    partial void OnidpedidoChanged();
    partial void OnidprodutoChanging(int value);
    partial void OnidprodutoChanged();
    partial void OnquantidadeChanging(decimal value);
    partial void OnquantidadeChanged();
    partial void OnvalorChanging(decimal value);
    partial void OnvalorChanged();
    partial void OnvalortotalChanging(decimal value);
    partial void OnvalortotalChanged();
    #endregion
		
		public itenspedido()
		{
			this._pedido = default(EntityRef<pedido>);
			this._produto = default(EntityRef<produto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iditenspedido", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int iditenspedido
		{
			get
			{
				return this._iditenspedido;
			}
			set
			{
				if ((this._iditenspedido != value))
				{
					this.OniditenspedidoChanging(value);
					this.SendPropertyChanging();
					this._iditenspedido = value;
					this.SendPropertyChanged("iditenspedido");
					this.OniditenspedidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idpedido", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idpedido
		{
			get
			{
				return this._idpedido;
			}
			set
			{
				if ((this._idpedido != value))
				{
					if (this._pedido.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidpedidoChanging(value);
					this.SendPropertyChanging();
					this._idpedido = value;
					this.SendPropertyChanged("idpedido");
					this.OnidpedidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idproduto", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idproduto
		{
			get
			{
				return this._idproduto;
			}
			set
			{
				if ((this._idproduto != value))
				{
					if (this._produto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidprodutoChanging(value);
					this.SendPropertyChanging();
					this._idproduto = value;
					this.SendPropertyChanged("idproduto");
					this.OnidprodutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantidade", DbType="Decimal(18,2) NOT NULL")]
		public decimal quantidade
		{
			get
			{
				return this._quantidade;
			}
			set
			{
				if ((this._quantidade != value))
				{
					this.OnquantidadeChanging(value);
					this.SendPropertyChanging();
					this._quantidade = value;
					this.SendPropertyChanged("quantidade");
					this.OnquantidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor", DbType="Money NOT NULL")]
		public decimal valor
		{
			get
			{
				return this._valor;
			}
			set
			{
				if ((this._valor != value))
				{
					this.OnvalorChanging(value);
					this.SendPropertyChanging();
					this._valor = value;
					this.SendPropertyChanged("valor");
					this.OnvalorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valortotal", DbType="Money NOT NULL")]
		public decimal valortotal
		{
			get
			{
				return this._valortotal;
			}
			set
			{
				if ((this._valortotal != value))
				{
					this.OnvalortotalChanging(value);
					this.SendPropertyChanging();
					this._valortotal = value;
					this.SendPropertyChanged("valortotal");
					this.OnvalortotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="pedido_itenspedido", Storage="_pedido", ThisKey="idpedido", OtherKey="idpedidos", IsForeignKey=true)]
		public pedido pedido
		{
			get
			{
				return this._pedido.Entity;
			}
			set
			{
				pedido previousValue = this._pedido.Entity;
				if (((previousValue != value) 
							|| (this._pedido.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._pedido.Entity = null;
						previousValue.itenspedidos.Remove(this);
					}
					this._pedido.Entity = value;
					if ((value != null))
					{
						value.itenspedidos.Add(this);
						this._idpedido = value.idpedidos;
					}
					else
					{
						this._idpedido = default(int);
					}
					this.SendPropertyChanged("pedido");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="produto_itenspedido", Storage="_produto", ThisKey="idproduto", OtherKey="idprodutos", IsForeignKey=true)]
		public produto produto
		{
			get
			{
				return this._produto.Entity;
			}
			set
			{
				produto previousValue = this._produto.Entity;
				if (((previousValue != value) 
							|| (this._produto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._produto.Entity = null;
						previousValue.itenspedidos.Remove(this);
					}
					this._produto.Entity = value;
					if ((value != null))
					{
						value.itenspedidos.Add(this);
						this._idproduto = value.idprodutos;
					}
					else
					{
						this._idproduto = default(int);
					}
					this.SendPropertyChanged("produto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pedidos")]
	public partial class pedido : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idpedidos;
		
		private int _idcliente;
		
		private System.Nullable<decimal> _valortotal;
		
		private int _statuspedido;
		
		private System.Nullable<System.DateTime> _data;
		
		private System.Nullable<System.DateTime> _dataliberacao;
		
		private System.Nullable<System.DateTime> _dataentregue;
		
		private System.Nullable<System.DateTime> _datamodificacao;
		
		private System.Nullable<System.DateTime> _datapagamento;
		
		private EntitySet<itenspedido> _itenspedidos;
		
		private EntityRef<cliente> _cliente;
		
		private EntityRef<statuspedido> _statuspedido1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidpedidosChanging(int value);
    partial void OnidpedidosChanged();
    partial void OnidclienteChanging(int value);
    partial void OnidclienteChanged();
    partial void OnvalortotalChanging(System.Nullable<decimal> value);
    partial void OnvalortotalChanged();
    partial void OnstatuspedidoChanging(int value);
    partial void OnstatuspedidoChanged();
    partial void OndataChanging(System.Nullable<System.DateTime> value);
    partial void OndataChanged();
    partial void OndataliberacaoChanging(System.Nullable<System.DateTime> value);
    partial void OndataliberacaoChanged();
    partial void OndataentregueChanging(System.Nullable<System.DateTime> value);
    partial void OndataentregueChanged();
    partial void OndatamodificacaoChanging(System.Nullable<System.DateTime> value);
    partial void OndatamodificacaoChanged();
    partial void OndatapagamentoChanging(System.Nullable<System.DateTime> value);
    partial void OndatapagamentoChanged();
    #endregion
		
		public pedido()
		{
			this._itenspedidos = new EntitySet<itenspedido>(new Action<itenspedido>(this.attach_itenspedidos), new Action<itenspedido>(this.detach_itenspedidos));
			this._cliente = default(EntityRef<cliente>);
			this._statuspedido1 = default(EntityRef<statuspedido>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idpedidos", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idpedidos
		{
			get
			{
				return this._idpedidos;
			}
			set
			{
				if ((this._idpedidos != value))
				{
					this.OnidpedidosChanging(value);
					this.SendPropertyChanging();
					this._idpedidos = value;
					this.SendPropertyChanged("idpedidos");
					this.OnidpedidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idcliente", DbType="Int NOT NULL")]
		public int idcliente
		{
			get
			{
				return this._idcliente;
			}
			set
			{
				if ((this._idcliente != value))
				{
					if (this._cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidclienteChanging(value);
					this.SendPropertyChanging();
					this._idcliente = value;
					this.SendPropertyChanged("idcliente");
					this.OnidclienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valortotal", DbType="Money")]
		public System.Nullable<decimal> valortotal
		{
			get
			{
				return this._valortotal;
			}
			set
			{
				if ((this._valortotal != value))
				{
					this.OnvalortotalChanging(value);
					this.SendPropertyChanging();
					this._valortotal = value;
					this.SendPropertyChanged("valortotal");
					this.OnvalortotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_statuspedido", DbType="Int NOT NULL")]
		public int statuspedido
		{
			get
			{
				return this._statuspedido;
			}
			set
			{
				if ((this._statuspedido != value))
				{
					if (this._statuspedido1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnstatuspedidoChanging(value);
					this.SendPropertyChanging();
					this._statuspedido = value;
					this.SendPropertyChanged("statuspedido");
					this.OnstatuspedidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data", DbType="DateTime")]
		public System.Nullable<System.DateTime> data
		{
			get
			{
				return this._data;
			}
			set
			{
				if ((this._data != value))
				{
					this.OndataChanging(value);
					this.SendPropertyChanging();
					this._data = value;
					this.SendPropertyChanged("data");
					this.OndataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataliberacao", DbType="DateTime")]
		public System.Nullable<System.DateTime> dataliberacao
		{
			get
			{
				return this._dataliberacao;
			}
			set
			{
				if ((this._dataliberacao != value))
				{
					this.OndataliberacaoChanging(value);
					this.SendPropertyChanging();
					this._dataliberacao = value;
					this.SendPropertyChanged("dataliberacao");
					this.OndataliberacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataentregue", DbType="DateTime")]
		public System.Nullable<System.DateTime> dataentregue
		{
			get
			{
				return this._dataentregue;
			}
			set
			{
				if ((this._dataentregue != value))
				{
					this.OndataentregueChanging(value);
					this.SendPropertyChanging();
					this._dataentregue = value;
					this.SendPropertyChanged("dataentregue");
					this.OndataentregueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datamodificacao", DbType="DateTime")]
		public System.Nullable<System.DateTime> datamodificacao
		{
			get
			{
				return this._datamodificacao;
			}
			set
			{
				if ((this._datamodificacao != value))
				{
					this.OndatamodificacaoChanging(value);
					this.SendPropertyChanging();
					this._datamodificacao = value;
					this.SendPropertyChanged("datamodificacao");
					this.OndatamodificacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datapagamento", DbType="DateTime")]
		public System.Nullable<System.DateTime> datapagamento
		{
			get
			{
				return this._datapagamento;
			}
			set
			{
				if ((this._datapagamento != value))
				{
					this.OndatapagamentoChanging(value);
					this.SendPropertyChanging();
					this._datapagamento = value;
					this.SendPropertyChanged("datapagamento");
					this.OndatapagamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="pedido_itenspedido", Storage="_itenspedidos", ThisKey="idpedidos", OtherKey="idpedido")]
		public EntitySet<itenspedido> itenspedidos
		{
			get
			{
				return this._itenspedidos;
			}
			set
			{
				this._itenspedidos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cliente_pedido", Storage="_cliente", ThisKey="idcliente", OtherKey="idclientes", IsForeignKey=true)]
		public cliente cliente
		{
			get
			{
				return this._cliente.Entity;
			}
			set
			{
				cliente previousValue = this._cliente.Entity;
				if (((previousValue != value) 
							|| (this._cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._cliente.Entity = null;
						previousValue.pedidos.Remove(this);
					}
					this._cliente.Entity = value;
					if ((value != null))
					{
						value.pedidos.Add(this);
						this._idcliente = value.idclientes;
					}
					else
					{
						this._idcliente = default(int);
					}
					this.SendPropertyChanged("cliente");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="statuspedido_pedido", Storage="_statuspedido1", ThisKey="statuspedido", OtherKey="idstatus", IsForeignKey=true)]
		public statuspedido statuspedido1
		{
			get
			{
				return this._statuspedido1.Entity;
			}
			set
			{
				statuspedido previousValue = this._statuspedido1.Entity;
				if (((previousValue != value) 
							|| (this._statuspedido1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._statuspedido1.Entity = null;
						previousValue.pedidos.Remove(this);
					}
					this._statuspedido1.Entity = value;
					if ((value != null))
					{
						value.pedidos.Add(this);
						this._statuspedido = value.idstatus;
					}
					else
					{
						this._statuspedido = default(int);
					}
					this.SendPropertyChanged("statuspedido1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_itenspedidos(itenspedido entity)
		{
			this.SendPropertyChanging();
			entity.pedido = this;
		}
		
		private void detach_itenspedidos(itenspedido entity)
		{
			this.SendPropertyChanging();
			entity.pedido = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.produtos")]
	public partial class produto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idprodutos;
		
		private string _nome;
		
		private int _idcategoria;
		
		private string _marca;
		
		private string _descricao;
		
		private System.Nullable<decimal> _valorvenda;
		
		private System.Nullable<decimal> _valorcompra;
		
		private System.Nullable<decimal> _saldoestoque;
		
		private EntitySet<itenspedido> _itenspedidos;
		
		private EntityRef<categoria> _categoria;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidprodutosChanging(int value);
    partial void OnidprodutosChanged();
    partial void OnnomeChanging(string value);
    partial void OnnomeChanged();
    partial void OnidcategoriaChanging(int value);
    partial void OnidcategoriaChanged();
    partial void OnmarcaChanging(string value);
    partial void OnmarcaChanged();
    partial void OndescricaoChanging(string value);
    partial void OndescricaoChanged();
    partial void OnvalorvendaChanging(System.Nullable<decimal> value);
    partial void OnvalorvendaChanged();
    partial void OnvalorcompraChanging(System.Nullable<decimal> value);
    partial void OnvalorcompraChanged();
    partial void OnsaldoestoqueChanging(System.Nullable<decimal> value);
    partial void OnsaldoestoqueChanged();
    #endregion
		
		public produto()
		{
			this._itenspedidos = new EntitySet<itenspedido>(new Action<itenspedido>(this.attach_itenspedidos), new Action<itenspedido>(this.detach_itenspedidos));
			this._categoria = default(EntityRef<categoria>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idprodutos", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idprodutos
		{
			get
			{
				return this._idprodutos;
			}
			set
			{
				if ((this._idprodutos != value))
				{
					this.OnidprodutosChanging(value);
					this.SendPropertyChanging();
					this._idprodutos = value;
					this.SendPropertyChanged("idprodutos");
					this.OnidprodutosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="VarChar(45)")]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this.OnnomeChanging(value);
					this.SendPropertyChanging();
					this._nome = value;
					this.SendPropertyChanged("nome");
					this.OnnomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idcategoria", DbType="Int NOT NULL")]
		public int idcategoria
		{
			get
			{
				return this._idcategoria;
			}
			set
			{
				if ((this._idcategoria != value))
				{
					if (this._categoria.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidcategoriaChanging(value);
					this.SendPropertyChanging();
					this._idcategoria = value;
					this.SendPropertyChanged("idcategoria");
					this.OnidcategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_marca", DbType="VarChar(45)")]
		public string marca
		{
			get
			{
				return this._marca;
			}
			set
			{
				if ((this._marca != value))
				{
					this.OnmarcaChanging(value);
					this.SendPropertyChanging();
					this._marca = value;
					this.SendPropertyChanged("marca");
					this.OnmarcaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descricao", DbType="VarChar(45)")]
		public string descricao
		{
			get
			{
				return this._descricao;
			}
			set
			{
				if ((this._descricao != value))
				{
					this.OndescricaoChanging(value);
					this.SendPropertyChanging();
					this._descricao = value;
					this.SendPropertyChanged("descricao");
					this.OndescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valorvenda", DbType="Money")]
		public System.Nullable<decimal> valorvenda
		{
			get
			{
				return this._valorvenda;
			}
			set
			{
				if ((this._valorvenda != value))
				{
					this.OnvalorvendaChanging(value);
					this.SendPropertyChanging();
					this._valorvenda = value;
					this.SendPropertyChanged("valorvenda");
					this.OnvalorvendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valorcompra", DbType="Money")]
		public System.Nullable<decimal> valorcompra
		{
			get
			{
				return this._valorcompra;
			}
			set
			{
				if ((this._valorcompra != value))
				{
					this.OnvalorcompraChanging(value);
					this.SendPropertyChanging();
					this._valorcompra = value;
					this.SendPropertyChanged("valorcompra");
					this.OnvalorcompraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saldoestoque", DbType="Decimal(6,2)")]
		public System.Nullable<decimal> saldoestoque
		{
			get
			{
				return this._saldoestoque;
			}
			set
			{
				if ((this._saldoestoque != value))
				{
					this.OnsaldoestoqueChanging(value);
					this.SendPropertyChanging();
					this._saldoestoque = value;
					this.SendPropertyChanged("saldoestoque");
					this.OnsaldoestoqueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="produto_itenspedido", Storage="_itenspedidos", ThisKey="idprodutos", OtherKey="idproduto")]
		public EntitySet<itenspedido> itenspedidos
		{
			get
			{
				return this._itenspedidos;
			}
			set
			{
				this._itenspedidos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="categoria_produto", Storage="_categoria", ThisKey="idcategoria", OtherKey="idcategorias", IsForeignKey=true)]
		public categoria categoria
		{
			get
			{
				return this._categoria.Entity;
			}
			set
			{
				categoria previousValue = this._categoria.Entity;
				if (((previousValue != value) 
							|| (this._categoria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._categoria.Entity = null;
						previousValue.produtos.Remove(this);
					}
					this._categoria.Entity = value;
					if ((value != null))
					{
						value.produtos.Add(this);
						this._idcategoria = value.idcategorias;
					}
					else
					{
						this._idcategoria = default(int);
					}
					this.SendPropertyChanged("categoria");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_itenspedidos(itenspedido entity)
		{
			this.SendPropertyChanging();
			entity.produto = this;
		}
		
		private void detach_itenspedidos(itenspedido entity)
		{
			this.SendPropertyChanging();
			entity.produto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.usuarios")]
	public partial class usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _login;
		
		private string _senha;
		
		private bool _admin;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnloginChanging(string value);
    partial void OnloginChanged();
    partial void OnsenhaChanging(string value);
    partial void OnsenhaChanged();
    partial void OnadminChanging(bool value);
    partial void OnadminChanged();
    #endregion
		
		public usuario()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_login", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string login
		{
			get
			{
				return this._login;
			}
			set
			{
				if ((this._login != value))
				{
					this.OnloginChanging(value);
					this.SendPropertyChanging();
					this._login = value;
					this.SendPropertyChanged("login");
					this.OnloginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_senha", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string senha
		{
			get
			{
				return this._senha;
			}
			set
			{
				if ((this._senha != value))
				{
					this.OnsenhaChanging(value);
					this.SendPropertyChanging();
					this._senha = value;
					this.SendPropertyChanged("senha");
					this.OnsenhaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin", DbType="Bit NOT NULL")]
		public bool admin
		{
			get
			{
				return this._admin;
			}
			set
			{
				if ((this._admin != value))
				{
					this.OnadminChanging(value);
					this.SendPropertyChanging();
					this._admin = value;
					this.SendPropertyChanged("admin");
					this.OnadminChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
